on: push
name: 🚀 Deploy website via FTPS
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 🔨 Build Project
        run: |
          npm install
          npm run generate

      - name: 🔒 Store Artifact on GH
        uses: actions/upload-artifact@v3
        with:
          name: Nuxt-Generate
          path: public/

      - name: 📂 Sync files (FTPS)
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.bytecamp.net
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ./public/
          dry-run: true
          protocol: ftps
