on:
  push:
    branches:
      - main
name: 🚀 Deploy website via FTPS
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: 🔨 Build Project
        run: |
          npm install
          npm run generate

      - name: 🔒 Store Artifact on GH
        uses: actions/upload-artifact@v3
        with:
          name: Svelte-Static
          path: public/

      - name: 📂 Sync files (FTPS)
        uses: SamKirkland/FTP-Deploy-Action@4.3.4
        with:
          server: ftp.bytecamp.net
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ./public/
          protocol: ftps
          state-name: do_not_edit_any_file-ftp-deploy-sync-state.json
          dry-run: true
